### ISSUE TITLE
Atari/Breakout render issue

### ISSUE THREAD

**Issue by luminous-123** [aai-institute/tianshou#1007]
- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:

I want to render atari/breakout-v5, but raise NotImplementedError
```bash
python test_ppo.py --task BreakoutNoFrameskip-v4 --logdir /root/autodl-tmp/test/ --render 1
```
Traceback (most recent call last):
  File "/root/code/Stolen-RL-Data/tianshou-origin/examples/atari/test_ppo.py", line 199, in <module>
    test_ppo(get_args())
  File "/root/code/Stolen-RL-Data/tianshou-origin/examples/atari/test_ppo.py", line 194, in test_ppo
    result = test_collector.trigger_collect(n_episode=args.test_num, render=args.render)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/tianshou/lib/python3.11/site-packages/tianshou/data/collector.py", line 392, in trigger_collect
    self.env.render()
  File "/root/miniconda3/envs/tianshou/lib/python3.11/site-packages/gymnasium/core.py", line 196, in render
    raise NotImplementedError
NotImplementedError

**Comment by MischaPanch** [comment]
Did you run this from the current master branch?
