### ISSUE TITLE
UnboundLocalError: cannot access local variable 'obs_space_dtype'  in atari_wrapper.py

### ISSUE THREAD

**Issue by zhuyuanyang** [aai-institute/tianshou#1111]
Traceback (most recent call last):
  File "/home/xxx/Desktop/ts/atari_dqn.py", line 262, in <module>
    test_dqn(get_args())
  File "/home/xxx/Desktop/ts/atari_dqn.py", line 87, in test_dqn
    env, train_envs, test_envs = make_atari_env(
                                 ^^^^^^^^^^^^^^^
  File "/home/xxx/Desktop/ts/examples/atari/atari_wrapper.py", line 381, in make_atari_env
    envs = env_factory.create_envs(training_num, test_num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/Desktop/ts/tianshou/highlevel/env.py", line 393, in create_envs
    env = self.create_env(EnvMode.TRAIN)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/Desktop/ts/examples/atari/atari_wrapper.py", line 414, in create_env
    return wrap_deepmind(
           ^^^^^^^^^^^^^^
  File "/home/xxx/Desktop/ts/examples/atari/atari_wrapper.py", line 356, in wrap_deepmind
    wrapped_env = WarpFrame(wrapped_env)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/Desktop/ts/examples/atari/atari_wrapper.py", line 212, in __init__
    dtype=obs_space_dtype,
          ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'obs_space_dtype' where it is not associated with a value

**Comment by MischaPanch** [comment]
Thanks for reporting, there was a typo in the type-checking of the observation space. Fixed in [049907d](https://github.com/thu-ml/tianshou/commit/049907d9abec6f9121f2d11c80899912de7f76dd)
