### ISSUE TITLE
get_env_attr not working in SubprocVectorEnv?

### ISSUE THREAD

**Issue by HYB777** [aai-institute/tianshou#1153]
I want to obtain some attributions from my custom environ, when I use DummyVectorEnv, get_env_attr is working.

But for SubprocVectorEnv, it seem not working? It report the following errors:

> Process Process-1:
Traceback (most recent call last):
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/env/worker/subproc.py", line 114, in _worker
    p.send(getattr(env, data) if hasattr(env, data) else None)
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'config_valve.<locals>.<lambda>'
Traceback (most recent call last):
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a8746349bf74>", line 1, in <cell line: 1>
    train_env.get_env_attr('simulator')
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/env/venvs.py", line 221, in get_env_attr
    return [self.workers[j].get_env_attr(key) for j in id]
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/env/venvs.py", line 221, in <listcomp>
    return [self.workers[j].get_env_attr(key) for j in id]
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/env/worker/subproc.py", line 152, in get_env_attr
    return self.parent_remote.recv()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

How could I solve it?

**Comment by Trinkle23897** [comment]
`AttributeError: Can't pickle local object 'config_valve..'` did you use lambda expression for `config_value`? Could you provide how you set `config_value`?

**Comment by HYB777** [comment]
> `AttributeError: Can't pickle local object 'config_valve..'` did you use lambda expression for `config_value`? Could you provide how you set `config_value`?

What does the `config_value` refer to? If you mean the paramter `env_fns` in `SubprocVectorEnv`, I was actually using a lambda expression, as follows:
`

    train_env_ = [lambda port=i: get_env(
        problem_config(
            problem=args.problem,
            prefix=args.prefix + '_train_port%d' % port,
            state_dir='state_dir',
            result_dir='result_dir',
            error_dir='error_dir',
            msh_dir='msh_dir',
            max_len=args.max_len,
            penalty=args.penalty,
            phase='train',
            local=args.prefix + '_train_port%d' % port,
            port=port,
        )
    ) for i in range(2036, 2036 + args.training_num)]
`

**Comment by MischaPanch** [comment]
Yes, lambdas are not picklable. One could maybe set things to use cloudpickle, which can deal with lambdas, but for now it's better if you just don't use lambdas for that part of the code.

**Comment by MischaPanch** [comment]
Sorry for the late reply @HYB777 , I was off tianhou for a bit but am back now

**Comment by MischaPanch** [comment]
Closing as answered
