### ISSUE TITLE
I use pybullet to creat a env and use SubprocVectorEnv. When implement obs = train_envs.reset(), there are some mistakes.

### ISSUE THREAD

**Issue by caimingxue** [aai-institute/tianshou#477]
train_envs = SubprocVectorEnv(
        [lambda: env for _ in range(1)]
    )
    obs = train_envs.reset()
------------------------------
  def reset(self):
        p.resetSimulation(physicsClientId=self._physics_client_id)    
        # p.resetSimulation()
        p.setGravity(0., 0., -9.8, physicsClientId=self._physics_client_id)
        p.setRealTimeSimulation(0)

pybullet build time: Jun 15 2021 21:35:58
Process Process-1:
Traceback (most recent call last):
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/site-packages/tianshou/env/worker/subproc.py", line 95, in _worker
    obs = env.reset()
  File "/Users/cmx/github_project/tianshou-bullet/test_env/mag_robot_env.py", line 100, in reset
    p.resetSimulation()
pybullet.error: Not connected to physics server.
Traceback (most recent call last):
  File "/Users/cmx/github_project/tianshou-bullet/test_env/mag_robot_env.py", line 190, in <module>
    obs = train_envs.reset()
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/site-packages/tianshou/env/venvs.py", line 173, in reset
    obs_list = [self.workers[i].reset() for i in id]
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/site-packages/tianshou/env/venvs.py", line 173, in <listcomp>
    obs_list = [self.workers[i].reset() for i in id]
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/site-packages/tianshou/env/worker/subproc.py", line 165, in reset
    obs = self.parent_remote.recv()
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/cmx/miniforge3/envs/tianshou_env/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

**Comment by Trinkle23897** [comment]
same as #436

**Comment by Trinkle23897** [comment]
Btw, if you use only one environment, why not use DummyVectorEnv?
