### ISSUE TITLE
h5py ImportError

### ISSUE THREAD

**Issue by houmaolin** [aai-institute/tianshou#479]
```python
Traceback (most recent call last):
  File "mujoco_sac.py", line 13, in <module>
    from tianshou.data import Collector, ReplayBuffer, VectorReplayBuffer
  File "/root/anaconda3/envs/erl/lib/python3.8/site-packages/tianshou/__init__.py", line 1, in <module>
    from tianshou import data, env, exploration, policy, trainer, utils
  File "/root/anaconda3/envs/erl/lib/python3.8/site-packages/tianshou/data/__init__.py", line 5, in <module>
    from tianshou.data.utils.converter import to_numpy, to_torch, to_torch_as
  File "/root/anaconda3/envs/erl/lib/python3.8/site-packages/tianshou/data/utils/converter.py", line 6, in <module>
    import h5py
  File "/root/anaconda3/envs/erl/lib/python3.8/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/root/anaconda3/envs/erl/lib/python3.8/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /root/anaconda3/envs/erl/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
```

**Comment by Trinkle23897** [comment]
It seems like it is a h5py related issue. Have you tried `pip install h5py==2.10.0`?

**Comment by Trinkle23897** [comment]
https://github.com/h5py/h5py/issues/1880

**Comment by houmaolin** [comment]
> It seems like it is a h5py related issue. Have you tried `pip install h5py==2.10.0`?

thanks a lot

**Comment by luckywlj** [comment]
It is OK. Thank you very much!
