### ISSUE TITLE
The Discrete actor reports an error when processing gym.env.space.Discrete data type: IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by link-zju** [aai-institute/tianshou#488]
The error recurrence script is following. 
```python
import gym
import torch
import numpy as np
import tianshou as ts

from tianshou.utils.net.common import Net
from torch.nn import ReLU
from torch.optim import Adam
from torch.optim import SGD
from tianshou.utils.net.discrete import Critic, Actor

def main(task, epoch, activation, optim, lr, clip, batch_size, device):
    hidden_sizes = [64, 64, 64]
    train_num, test_num = 10, 10
    buffer_size = 20000
    step_per_epoch, step_per_collect = 10000, 10000
    repeat_per_collect = 2

    env = gym.make(task)
    state_shape = env.observation_space.shape or env.observation_space.n
    action_shape = env.action_space.shape or env.action_space.n
    train_envs = ts.env.DummyVectorEnv([lambda: gym.make(task) for _ in range(train_num)])
    test_envs = ts.env.DummyVectorEnv([lambda: gym.make(task) for _ in range(test_num)])

    actor_net = Net(state_shape=state_shape, activation=activation, hidden_sizes=hidden_sizes, device=device).to(device)
    actor = Actor(actor_net, action_shape, device=device).to(device)
    critic_net = Net(state_shape=state_shape, activation=activation, hidden_sizes=hidden_sizes, device=device).to(device)
    critic = Critic(critic_net, device=device).to(device)
    
    for m in list(actor_net.modules()) + list(critic_net.modules()):
        if isinstance(m, torch.nn.Linear):
            # orthogonal initialization
            torch.nn.init.orthogonal_(m.weight, gain=np.sqrt(2))
            torch.nn.init.zeros_(m.bias)
    
    if optim == SGD:    
        optim1 = optim([{'params': actor.parameters(), 'lr': lr},
                    {'params': critic.parameters(), 'lr': lr}], lr=lr, momentum=0.9)
    else:
        optim1 = optim([{'params': actor.parameters(), 'lr': lr},
                    {'params': critic.parameters(), 'lr': lr}], lr=lr)
    

    dist = torch.distributions.Categorical
    policy = ts.policy.PPOPolicy(actor=actor, critic=critic, optim=optim1, dist_fn=dist, eps_clip=clip)
    train_collector = ts.data.Collector(policy, train_envs, ts.data.VectorReplayBuffer(buffer_size, train_num))
    test_collector = ts.data.Collector(policy, test_envs) 

    result = ts.trainer.onpolicy_trainer(policy, 
                                        train_collector, 
                                        test_collector, 
                                        epoch, 
                                        step_per_epoch, 
                                        repeat_per_collect,
                                        test_num, 
                                        batch_size, 
                                        step_per_collect,
                                        stop_fn=lambda mean_rewards: mean_rewards >= 200)

if __name__ == '__main__':

    device = torch.device("cpu")
    main(task='FrozenLake-v1', activation=ReLU, optim=Adam, lr=1e-3, clip=0.5, batch_size=512, epoch=20, device=device)
```

```python
Traceback (most recent call last):
  File "error_recurrence.py", line 69, in <module>
    main(task='FrozenLake-v1', activation=ReLU, optim=Adam, lr=1e-3, clip=0.5, batch_size=512, epoch=20, device=device)
  File "error_recurrence.py", line 53, in main
    result = ts.trainer.onpolicy_trainer(policy, 
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/trainer/onpolicy.py", line 107, in onpolicy_trainer
    test_result = test_episode(
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/trainer/utils.py", line 27, in test_episode
    result = collector.collect(n_episode=n_episode)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/data/collector.py", line 220, in collect
    result = self.policy(self.data, last_state)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/policy/modelfree/pg.py", line 110, in forward
    logits, h = self.actor(batch.obs, state=state)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/utils/net/discrete.py", line 62, in forward
    logits, h = self.preprocess(s, state)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/utils/net/common.py", line 196, in forward
    logits = self.model(s)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-2021.05/envs/rllk/lib/python3.8/site-packages/tianshou/utils/net/common.py", line 98, in forward
    return self.model(s.flatten(1))  # type: ignore
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by Trinkle23897** [comment]
It is because the observation is a single numeric value in `FrozenLake-v1`. Most of the time we assume the observation is a numpy array instead of a single value.

Here is the solution: add an `ObservationWrapper` that converts the observation into a numpy array. I only add `FixDim` in your script:

```python
import gym
import torch
import numpy as np
import tianshou as ts

from tianshou.utils.net.common import Net
from torch.nn import ReLU
from torch.optim import Adam
from torch.optim import SGD
from tianshou.utils.net.discrete import Critic, Actor


class FixDim(gym.ObservationWrapper):
    def __init__(self, env):
        super().__init__(env)
        self.observation_space = gym.spaces.Box(0, env.observation_space.n - 1, shape=(1,))

    def observation(self, frame):
        return np.array([frame])


def main(task, epoch, activation, optim, lr, clip, batch_size, device):
    hidden_sizes = [64, 64, 64]
    train_num, test_num = 10, 10
    buffer_size = 20000
    step_per_epoch, step_per_collect = 10000, 10000
    repeat_per_collect = 2

    env = FixDim(gym.make(task))
    print(env.observation_space)
    print(env.action_space)
    state_shape = env.observation_space.shape or env.observation_space.n
    action_shape = env.action_space.shape or env.action_space.n
    print(state_shape, action_shape)
    train_envs = ts.env.DummyVectorEnv(
        [lambda: FixDim(gym.make(task)) for _ in range(train_num)])
    test_envs = ts.env.DummyVectorEnv(
        [lambda: FixDim(gym.make(task)) for _ in range(test_num)])

    actor_net = Net(state_shape=state_shape, activation=activation,
                    hidden_sizes=hidden_sizes, device=device).to(device)
    actor = Actor(actor_net, action_shape, device=device).to(device)
    critic_net = Net(state_shape=state_shape, activation=activation,
                     hidden_sizes=hidden_sizes, device=device).to(device)
    critic = Critic(critic_net, device=device).to(device)

    for m in list(actor_net.modules()) + list(critic_net.modules()):
        if isinstance(m, torch.nn.Linear):
            # orthogonal initialization
            torch.nn.init.orthogonal_(m.weight, gain=np.sqrt(2))
            torch.nn.init.zeros_(m.bias)

    if optim == SGD:
        optim1 = optim([{'params': actor.parameters(), 'lr': lr},
                        {'params': critic.parameters(), 'lr': lr}], lr=lr, momentum=0.9)
    else:
        optim1 = optim([{'params': actor.parameters(), 'lr': lr},
                        {'params': critic.parameters(), 'lr': lr}], lr=lr)

    dist = torch.distributions.Categorical
    policy = ts.policy.PPOPolicy(
        actor=actor, critic=critic, optim=optim1, dist_fn=dist, eps_clip=clip)
    print(policy)
    train_collector = ts.data.Collector(
        policy, train_envs, ts.data.VectorReplayBuffer(buffer_size, train_num))
    test_collector = ts.data.Collector(policy, test_envs)

    result = ts.trainer.onpolicy_trainer(policy,
                                         train_collector,
                                         test_collector,
                                         epoch,
                                         step_per_epoch,
                                         repeat_per_collect,
                                         test_num,
                                         batch_size,
                                         step_per_collect,
                                         stop_fn=lambda mean_rewards: mean_rewards >= 200)


if __name__ == '__main__':
    device = torch.device("cpu")
    main(task='FrozenLake-v1', activation=ReLU, optim=Adam,
         lr=1e-3, clip=0.5, batch_size=512, epoch=20, device=device)
```

**Comment by link-zju** [comment]
Okay, it works well now. Many thanks!
