### ISSUE TITLE
why i can't get action by using policy(batch)?

### ISSUE THREAD

**Issue by minttttt** [aai-institute/tianshou#528]
why i can't get action by using policy(batch)?
I have tried the mujoco_ddpg.py examples successfully(This can prove to be not a problem with environment configuration).
any help would be greatly appreciated. Thanks!
tianshou version:0.4.5,ubuntu20.04,python 3.8

Here is my code:
```python
#!/usr/bin/env python3

import argparse

import gym
import numpy as np
import torch

from tianshou.env import SubprocVectorEnv
from tianshou.exploration import GaussianNoise
from tianshou.policy import DDPGPolicy
from tianshou.utils.net.common import Net
from tianshou.utils.net.continuous import Actor, Critic
from tianshou.data import Batch

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--task', type=str, default='Ant-v3')
    parser.add_argument('--seed', type=int, default=0)
    parser.add_argument('--buffer-size', type=int, default=1000000)
    parser.add_argument('--hidden-sizes', type=int, nargs='*', default=[256, 256])
    parser.add_argument('--actor-lr', type=float, default=1e-3)
    parser.add_argument('--critic-lr', type=float, default=1e-3)
    parser.add_argument('--gamma', type=float, default=0.99)
    parser.add_argument('--tau', type=float, default=0.005)
    parser.add_argument('--exploration-noise', type=float, default=0.1)
    parser.add_argument("--start-timesteps", type=int, default=25000)
    parser.add_argument('--epoch', type=int, default=200)
    parser.add_argument('--step-per-epoch', type=int, default=5000)
    parser.add_argument('--step-per-collect', type=int, default=1)
    parser.add_argument('--update-per-step', type=int, default=1)
    parser.add_argument('--n-step', type=int, default=1)
    parser.add_argument('--batch-size', type=int, default=256)
    parser.add_argument('--training-num', type=int, default=1)
    parser.add_argument('--test-num', type=int, default=10)
    parser.add_argument('--logdir', type=str, default='log')
    parser.add_argument('--render', type=float, default=0.)
    parser.add_argument(
        '--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu'
    )
    parser.add_argument('--resume-path', type=str, default=None)
    parser.add_argument(
        '--watch',
        default=False,
        action='store_true',
        help='watch the play of pre-trained policy only'
    )
    return parser.parse_args()


def test_ddpg(args=get_args()):
    env = gym.make(args.task)
    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.action_shape = env.action_space.shape or env.action_space.n
    args.max_action = env.action_space.high[0]
    args.exploration_noise = args.exploration_noise * args.max_action
    print("Observations shape:", args.state_shape)
    print("Actions shape:", args.action_shape)
    print("Action range:", np.min(env.action_space.low), np.max(env.action_space.high))

    train_envs = gym.make(args.task)
    test_envs = SubprocVectorEnv(
        [lambda: gym.make(args.task) for _ in range(args.test_num)]
    )

    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    train_envs.seed(args.seed)
    test_envs.seed(args.seed)

    net_a = Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device)
    actor = Actor(
        net_a, args.action_shape, max_action=args.max_action, device=args.device
    ).to(args.device)
    actor_optim = torch.optim.Adam(actor.parameters(), lr=args.actor_lr)
    net_c = Net(
        args.state_shape,
        args.action_shape,
        hidden_sizes=args.hidden_sizes,
        concat=True,
        device=args.device
    )
    critic = Critic(net_c, device=args.device).to(args.device)
    critic_optim = torch.optim.Adam(critic.parameters(), lr=args.critic_lr)
    policy = DDPGPolicy(
        actor,
        actor_optim,
        critic,
        critic_optim,
        tau=args.tau,
        gamma=args.gamma,
        exploration_noise=GaussianNoise(sigma=args.exploration_noise),
        estimation_step=args.n_step,
        action_space=env.action_space
    )

    data = Batch(
            obs={}, act={}, rew={}, done={}, obs_next={}, info={}, policy={}
    )
    data.obs = train_envs.reset()
    result = policy(data) # bug here
    print(result)
if __name__ == '__main__':
    test_ddpg()

```
Here is the output in terminal:
```
Observations shape: (111,)
Actions shape: (8,)
Action range: -1.0 1.0
Traceback (most recent call last):
  File "bug.py", line 104, in <module>
    test_ddpg()
  File "bug.py", line 101, in test_ddpg
    result = policy(data)
  File "/home/school20/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/school20/.local/lib/python3.8/site-packages/tianshou/policy/modelfree/ddpg.py", line 142, in forward
    actions, h = model(obs, state=state, info=batch.info)
  File "/home/school20/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/school20/.local/lib/python3.8/site-packages/tianshou/utils/net/continuous.py", line 61, in forward
    logits, h = self.preprocess(s, state)
  File "/home/school20/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/school20/.local/lib/python3.8/site-packages/tianshou/utils/net/common.py", line 195, in forward
    logits = self.model(s)
  File "/home/school20/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/school20/.local/lib/python3.8/site-packages/tianshou/utils/net/common.py", line 97, in forward
    return self.model(s.flatten(1))  # type: ignore
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

```

**Comment by Trinkle23897** [comment]
>     train_envs = gym.make(args.task)

This is a single environment instead of vectorized environment, so that the shape of `data.obs` doesn't contain the batch-size. Try this:

```python
In [12]:     data = Batch(
    ...:             obs={}, act={}, rew={}, done={}, obs_next={}, info={}, policy={}
    ...:     )
    ...:     data.obs = data.obs_next = test_envs.reset()

In [13]: policy(data)
Out[13]: 
Batch(
    act: tensor([[-0.0749,  0.0360, -0.0043, -0.0220, -0.0560,  0.1023, -0.0098, -0.0060],
                 [-0.0743,  0.0247, -0.0035, -0.0250, -0.0478,  0.1051, -0.0040, -0.0014],
                 [-0.0716,  0.0325, -0.0022, -0.0258, -0.0487,  0.0907, -0.0029, -0.0038],
                 [-0.0742,  0.0313,  0.0092, -0.0235, -0.0521,  0.1030, -0.0076, -0.0035],
                 [-0.0696,  0.0334,  0.0048, -0.0227, -0.0527,  0.1049, -0.0045, -0.0060],
                 [-0.0733,  0.0320, -0.0083, -0.0185, -0.0472,  0.0952, -0.0021, -0.0062],
                 [-0.0689,  0.0263, -0.0073, -0.0289, -0.0491,  0.1010, -0.0058, -0.0035],
                 [-0.0720,  0.0312, -0.0060, -0.0189, -0.0542,  0.1025, -0.0049, -0.0083],
                 [-0.0736,  0.0333, -0.0108, -0.0277, -0.0482,  0.0973, -0.0008, -0.0083],
                 [-0.0680,  0.0380, -0.0048, -0.0157, -0.0507,  0.0948, -0.0026, -0.0059]],
                device='cuda:0', grad_fn=<MulBackward0>),
    state: None,
)
```

**Comment by minttttt** [comment]
Thank you for your reply. 
But I'm still confused about what "the shape of data.obs doesn't contain the batch-size" means.
When I read the document, I thought I needed only one parameter “obs” to get the return value.

**Comment by Trinkle23897** [comment]
> When I read the document, I thought I needed only one parameter “obs” to get the return value.

Yes you're right. 

```python
In [19]:     data = Batch(
    ...:             obs={}, act={}, rew={}, done={}, obs_next={}, info={}, policy={}
    ...:     )
    ...:     data.obs = test_envs.reset()

In [20]: policy(data)
Out[20]: 
Batch(
    act: tensor([[-0.0725,  0.0334, -0.0001, -0.0242, -0.0545,  0.0988,  0.0011, -0.0059],
                 [-0.0725,  0.0305, -0.0052, -0.0180, -0.0527,  0.1003, -0.0029, -0.0062],
                 [-0.0649,  0.0317,  0.0058, -0.0245, -0.0535,  0.1025, -0.0058, -0.0023],
                 [-0.0756,  0.0299, -0.0010, -0.0218, -0.0549,  0.0984, -0.0099, -0.0078],
                 [-0.0748,  0.0334, -0.0028, -0.0279, -0.0529,  0.1014, -0.0066, -0.0039],
                 [-0.0738,  0.0302, -0.0034, -0.0249, -0.0545,  0.0985, -0.0012, -0.0064],
                 [-0.0701,  0.0287,  0.0061, -0.0209, -0.0552,  0.0996, -0.0007,  0.0010],
                 [-0.0715,  0.0330, -0.0100, -0.0177, -0.0504,  0.0968, -0.0009, -0.0037],
                 [-0.0705,  0.0336, -0.0030, -0.0206, -0.0487,  0.0994, -0.0028, -0.0034],
                 [-0.0722,  0.0293, -0.0023, -0.0296, -0.0544,  0.0936,  0.0040, -0.0082]],
                device='cuda:0', grad_fn=<MulBackward0>),
    state: None,
)
```

> But I'm still confused about what "the shape of data.obs doesn't contain the batch-size" means.

```python
In [21]: train_envs.reset().shape
Out[21]: (111,)

In [22]: test_envs.reset().shape
Out[22]: (10, 111)
```

There's only one env in train_envs and 10 envs in test_envs. If you want to make things work with this train_env:
```python
In [24]:     data = Batch(
    ...:             obs={}, act={}, rew={}, done={}, obs_next={}, info={}, policy={}
    ...:     )
    ...:     data.obs = train_envs.reset().reshape(1, -1)

In [25]: policy(data)
Out[25]: 
Batch(
    act: tensor([[-0.0628,  0.0345, -0.0081, -0.0264, -0.0443,  0.0973,  0.0009, -0.0063]],
                device='cuda:0', grad_fn=<MulBackward0>),
    state: None,
)
```

**Comment by minttttt** [comment]
I got it,thank you very much !
