### ISSUE TITLE
how to use policy.learn() directly?

### ISSUE THREAD

**Issue by minttttt** [aai-institute/tianshou#530]
I want to use `policy.learn(batch)` directly but failed.
i found the example function call is:
policy.update(size, buffer) -> batch, indices = buffer.sample(size) -> `policy.learn(batch)`
what is the difference between them?how to use it directly?
any help would be greatly appreciated. Thanks!

Here is my test code:
```python
import argparse

import gym
import numpy as np
import torch

from tianshou.data import Collector, ReplayBuffer
from tianshou.policy import DQNPolicy
from tianshou.utils.net.common import Net


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--task', type=str, default='CartPole-v0')
    parser.add_argument('--seed', type=int, default=1626)
    parser.add_argument('--eps-test', type=float, default=0.05)
    parser.add_argument('--eps-train', type=float, default=0.1)
    parser.add_argument('--buffer-size', type=int, default=20000)
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--gamma', type=float, default=0.9)
    parser.add_argument('--n-step', type=int, default=3)
    parser.add_argument('--target-update-freq', type=int, default=320)
    parser.add_argument('--epoch', type=int, default=20)
    parser.add_argument('--step-per-epoch', type=int, default=10000)
    parser.add_argument('--step-per-collect', type=int, default=10)
    parser.add_argument('--update-per-step', type=float, default=0.1)
    parser.add_argument('--batch-size', type=int, default=64)
    parser.add_argument(
        '--hidden-sizes', type=int, nargs='*', default=[128, 128, 128, 128]
    )
    parser.add_argument('--training-num', type=int, default=10)
    parser.add_argument('--test-num', type=int, default=100)
    parser.add_argument('--logdir', type=str, default='log')
    parser.add_argument('--render', type=float, default=0.)
    parser.add_argument('--prioritized-replay', action="store_true", default=False)
    parser.add_argument('--alpha', type=float, default=0.6)
    parser.add_argument('--beta', type=float, default=0.4)
    parser.add_argument(
        '--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu'
    )
    args = parser.parse_known_args()[0]
    return args


def test_dqn(args=get_args()):
    env = gym.make(args.task)
    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.action_shape = env.action_space.shape or env.action_space.n
    train_envs = gym.make(args.task)
    test_envs = gym.make(args.task)
    # seed
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    train_envs.seed(args.seed)
    test_envs.seed(args.seed)
    # model
    net = Net(
        args.state_shape,
        args.action_shape,
        hidden_sizes=args.hidden_sizes,
        device=args.device,
    ).to(args.device)
    optim = torch.optim.Adam(net.parameters(), lr=args.lr)
    policy = DQNPolicy(
        net,
        optim,
        args.gamma,
        args.n_step,
        target_update_freq=args.target_update_freq,
    )
    buf = ReplayBuffer(args.buffer_size)
    # collector
    train_collector = Collector(policy, train_envs, buf, exploration_noise=True)
    train_collector.collect(5000)

    policy.update(64, buf)
    print('test1')
    buf1 = buf.sample(64)[0]
    policy.learn(buf1)# failed
    print('test2')
    exit()

if __name__ == '__main__':
    test_dqn(get_args())
```

Here is the terminal output:
```bash
test1
Traceback (most recent call last):
  File "question.py", line 82, in <module>
    test_dqn(get_args())
  File "question.py", line 77, in test_dqn
    policy.learn(buf1)# failed
  File "/home/school20/.local/lib/python3.8/site-packages/tianshou/policy/modelfree/dqn.py", line 169, in learn
    r = to_torch_as(batch.returns.flatten(), q)
  File "/home/school20/.local/lib/python3.8/site-packages/tianshou/data/batch.py", line 205, in __getattr__
    return getattr(self.__dict__, key)
AttributeError: 'dict' object has no attribute 'returns'
```

**Comment by Trinkle23897** [comment]
https://tianshou.readthedocs.io/en/master/tutorials/concepts.html#policy

You need to call `update` function. That would call `process_fn -> learn -> post_process_fn`. process_fn in DQN will calculate returns and pass it to learn.

**Comment by minttttt** [comment]
Sorry, I missed it, thinking `process_fn` was a function that needs to be implemented by myself.
