### ISSUE TITLE
Save graph error

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#551]
- I have marked all applicable categories:
    + exception-raising bug
    + RL algorithm bug
    + documentation request (i.e. "X is missing from the documentation.")
    + new feature request
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.6.post1 1.10.2+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
When I use SACPolicy to learn:
```python
loss = policy.learn(b_ret)
```
Prompt the following error:

What should I do next?

```python
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Tony/Documents/yunpan/invest/2022/quant/code/SecuritiesTrading/HS300/SAC.py", line 312, in <module>
    main()
  File "D:/Tony/Documents/yunpan/invest/2022/quant/code/SecuritiesTrading/HS300/SAC.py", line 253, in main
    loss = policy.learn(b_ret)
  File "D:\Anaconda3\lib\site-packages\tianshou\policy\modelfree\sac.py", line 157, in learn
    td2, critic2_loss = self._mse_optimizer(
  File "D:\Anaconda3\lib\site-packages\tianshou\policy\modelfree\ddpg.py", line 155, in _mse_optimizer
    critic_loss.backward()
  File "D:\Anaconda3\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

**Comment by nuance1979** [comment]
It seems your are calling the `policy.learn()` method directly. This is usually not the right way to use tianshou. Take a look at the example script https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/mujoco_sac.py . From the error message, I suspect that you didn't construct your Actor and/or Critic nets correctly.

**Comment by jaried** [comment]
Thanks for your answer.
