### ISSUE TITLE
tianshou can not work when a list in 'info' of gym is used?

### ISSUE THREAD

**Issue by KeXue-NJU** [aai-institute/tianshou#582]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
My tianshou and gym version is 0.4.5, 0.21.0.
I use tianshou for my customed env, so I will save some helpful information as list in 'info'. 

However, when a list is used in 'info', it cannot work, and the exceptions are :

```python
  File "/xxx.py", line 219, in test_dqn
    train_collector.collect(n_episode=1)
  File "/lib/python3.7/site-packages/tianshou/data/collector.py", line 260, in collect
    self.data, buffer_ids=ready_env_ids
  File "/lib/python3.7/site-packages/tianshou/data/buffer/manager.py", line 154, in add
    self._meta[ptrs] = batch
  File "/lib/python3.7/site-packages/tianshou/data/batch.py", line 262, in __setitem__
    self.__dict__[key][index] = value[key]
  File "/lib/python3.7/site-packages/tianshou/data/batch.py", line 262, in __setitem__
    self.__dict__[key][index] = value[key]
ValueError: shape mismatch: value array of shape (1,2)  could not be broadcast to indexing result of shape (1,1) 
```
I'm absolutely sure about this, because when I remove the list in the 'info', it works again.

**Comment by Trinkle23897** [comment]
It's because Batch usually doesn't support a list with various lengths. The underlying implementation is to use a numpy array or torch tensor to store everything:
```python
In [13]: a = Batch(key=np.zeros([2, 3]))

In [14]: a[1] = Batch(key=[1, 2])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-3d114cb8f679> in <module>
----> 1 a[1] = Batch(key=[1, 2])

~/github/tianshou-new/tianshou/data/batch.py in __setitem__(self, index, value)
    263         for key, val in self.items():
    264             try:
--> 265                 self.__dict__[key][index] = value[key]
    266             except KeyError:
    267                 if isinstance(val, Batch):

ValueError: could not broadcast input array from shape (2,) into shape (3,)
```

However, if you use with `np.array([...], object)`, things would be different:
```python
In [15]: a = Batch(key=np.zeros([2], object))

In [16]: a[1] = Batch(key=[1, 2])

In [17]: a
Out[17]: 
Batch(
    key: array([0, array([1, 2])], dtype=object),
)

In [18]: a[0] = Batch(key=[1, 2])

In [19]: a
Out[19]: 
Batch(
    key: array([array([1, 2]), array([1, 2])], dtype=object),
)
In [20]: a[0] = Batch(key=[1, 2, 3])

In [21]: a
Out[21]: 
Batch(
    key: array([array([1, 2, 3]), array([1, 2])], dtype=object),
)
```

So the solution is to change the list to `np.array(list, object)`:
```python
In [25]: Batch.stack([Batch(key=np.array([1, 3, 4], object)), Batch(key=np.array([1, 2], dtype=object))])
/home/trinkle/github/tianshou-new/tianshou/data/batch.py:546: UserWarning: You are using tensors with different shape, fallback to dtype=object by default.
  warnings.warn(
Out[25]: 
Batch(
    key: array([array([1, 3, 4], dtype=object), array([1, 2], dtype=object)],
               dtype=object),
)
```

**Comment by KeXue-NJU** [comment]
Thanks alot!
