### ISSUE TITLE
ValueError in compute_nstep_return

### ISSUE THREAD

**Issue by bretsky** [aai-institute/tianshou#583]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Versions:

- Tianshou: 0.4.7
- Gym: 0.21.0
- Torch: 1.11.0+cu113
- numpy: 1.21.5
- Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
- Platform: win32

When training using the DQNPolicy, I get the following exception:

```python
Traceback (most recent call last):
  File "train_ts.py", line 66, in <module>
    logger=Logger(writer=torch.utils.tensorboard.SummaryWriter(log_dir=log_dir), train_interval=1, update_interval=1),
  File "D:\Programs\Python37\lib\site-packages\tianshou\trainer\offpolicy.py", line 129, in offpolicy_trainer
    return OffpolicyTrainer(*args, **kwargs).run()
  File "D:\Programs\Python37\lib\site-packages\tianshou\trainer\base.py", line 418, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "D:\Programs\Python37\lib\site-packages\tianshou\trainer\base.py", line 281, in __next__
    self.policy_update_fn(data, result)
  File "D:\Programs\Python37\lib\site-packages\tianshou\trainer\offpolicy.py", line 118, in policy_update_fn
    losses = self.policy.update(self.batch_size, self.train_collector.buffer)
  File "D:\Programs\Python37\lib\site-packages\tianshou\policy\base.py", line 272, in update
    batch = self.process_fn(batch, buffer, indices)
  File "D:\Programs\Python37\lib\site-packages\tianshou\policy\modelfree\dqn.py", line 101, in process_fn
    self._rew_norm
  File "D:\Programs\Python37\lib\site-packages\tianshou\policy\base.py", line 395, in compute_nstep_return
    target_q = _nstep_return(rew, end_flag, target_q, indices, gamma, n_step)
  File "D:\Programs\Python37\lib\site-packages\numba\np\arrayobj.py", line 1736, in normalize_reshape_value
    raise ValueError("total size of new array must be unchanged")
ValueError: total size of new array must be unchanged
```

Training code:
```python
num_envs = 1
train_envs = DummyVectorEnv([lambda: PettingZooEnv(parallel_to_aec(MyEnv(data))) for _ in range(num_envs)])
env = PettingZooEnv(parallel_to_aec(MyEnv(data)))

train_envs.seed(1)
test_envs = DummyVectorEnv([lambda: PettingZooEnv(parallel_to_aec(PokemonBattleEnv(generated_teams))) for _ in range(num_envs)])

print(gym.spaces.flatdim(env.observation_space['observation']))
print(env.action_space.n)
net = Net(
	gym.spaces.flatdim(env.observation_space['observation']),
	env.action_space.n,
	hidden_sizes=[8192, 8192],
	device="cuda",
).to("cuda")
optim = torch.optim.Adam(net.parameters(), lr=0.001)
gamma = 0.9
n_step = 1
target_update_freq = 10
policy = DQNPolicy(
	net,
	optim,
	gamma,
	n_step,
	target_update_freq=target_update_freq,
)


train_collector = Collector(policy, train_envs, VectorReplayBuffer(20000, 10), exploration_noise=True)
test_collector = Collector(policy, test_envs, exploration_noise=True)

result = offpolicy_trainer(
	policy,
	train_collector,
	test_collector,
	max_epoch=10,
	step_per_epoch=10,
	step_per_collect=10,
	update_per_step=0.1,
	episode_per_test=10,
	batch_size=16,
	train_fn=lambda epoch, env_step: policy.set_eps(0.1),
	test_fn=lambda epoch, env_step: policy.set_eps(0.05),
	stop_fn=lambda mean_reward: mean_reward > 0.5,
	logger=Logger(writer=torch.utils.tensorboard.SummaryWriter(log_dir=log_dir), train_interval=1, update_interval=1),
)

```

Any advice for how to resolve this would be greatly appreciated. If necessary I can share any additional code that is relevant.

**EDIT**
The issue seems to be on this line. The shape of `rew[now]` is `(16, 2)` which cannot be reshaped into `(16, 1)`
```python
returns = rew[now].reshape(bsz, 1) + gamma * returns
```

**Comment by Trinkle23897** [comment]
> The issue seems to be on this line. The shape of rew[now] is (16, 2) which cannot be reshaped into (16, 1)

Does this environment step two players simultaneously instead of stepping players one by one?

**Comment by bretsky** [comment]
Yes, the base environment steps two players simultaneously but my understanding was the `parallel_to_aec` wrapper converts it to stepping one by one. Is this incorrect?

**Comment by Trinkle23897** [comment]
I think it should work if this wrapper works correctly.

**Comment by bretsky** [comment]
I will look into the implementation. What should be the shape of `rew[now]`?

**Comment by Trinkle23897** [comment]
I think it should be (16, 1).

**Comment by bretsky** [comment]
```python
    def step(self, action: Any) -> Tuple[Dict, List[int], bool, Dict]:
        self.env.step(action)
        observation, rew, done, info = self.env.last()
        if isinstance(observation, dict) and 'action_mask' in observation:
            obs = {
                'agent_id': self.env.agent_selection,
                'obs': observation['observation'],
                'mask':
                [True if obm == 1 else False for obm in observation['action_mask']]
            }
        else:
            if isinstance(self.action_space, gym.spaces.Discrete):
                obs = {
                    'agent_id': self.env.agent_selection,
                    'obs': observation,
                    'mask': [True] * self.env.action_space(self.env.agent_selection).n
                }
            else:
                obs = {'agent_id': self.env.agent_selection, 'obs': observation}

        for agent_id, reward in self.env.rewards.items():
            self.rewards[self.agent_idx[agent_id]] = reward
        return obs, self.rewards, done, info
```

The wrapper appeared to be working correctly, however it seems that the last three lines of the step function in `pettingzoo_env.py` is causing this issue. Is there a reason we are iterating through all the `env.rewards` rather than using the `rew` reward returned from `self.env.last()`? Returning `obs, rew, done, info` instead seems to fix my issue.

**Comment by Trinkle23897** [comment]
`self.env.last()` is because of the pettingzoo API. Feel free to modify any part of the code (including pettingzoo_env.py) :)
