### ISSUE TITLE
How does the sac algorithm modify the initial value of alpha?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#649]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.8 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```

The `args.alpha` in the `sac demo` doesn't seem to work. How to modify the initial value of `alpha` in the `sac` algorithm?

**Comment by Trinkle23897** [comment]
Maybe you can change this line if you enable the auto_alpha? https://github.com/thu-ml/tianshou/blob/277138ca5b050518aacaaea367192f910fbe666d/examples/mujoco/mujoco_sac.py#L111

**Comment by jaried** [comment]
I have used this line of code.

I have auto_alpha enabled, how can I specify the initial value of alpha?
` parser.add_argument('--auto-alpha', type=int, default=1)`

**Comment by Trinkle23897** [comment]
I mean changing `torch.zeros(1, ...)` to `torch.zeros(math.log(args.alpha), ...)`

**Comment by jaried** [comment]
get TypeError:
```python
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-dbcc5ee189e2>", line 1, in <module>
    log_alpha = torch.zeros(math.log(args.alpha), requires_grad=True, device=args.device)
TypeError: zeros() received an invalid combination of arguments - got (float, requires_grad=bool, device=str), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

**Comment by Trinkle23897** [comment]
My bad. `torch.zeros(1, requires_grad=True, device=args.device) + math.log(args.alpha)`

**Comment by jaried** [comment]
It works. Thank you so much.

**Comment by jaried** [comment]
Got TypeError too:
```python
log_alpha = torch.zeros(1, requires_grad=True, device=args.device) + torch.tensor(np.log(args.alpha),
                                                                                  device=args.device)
alpha_optim = torch.optim.Adam([log_alpha], lr=args.alpha_lr)
```
```python
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-ecabcbc6c2a3>", line 1, in <module>
    alpha_optim = torch.optim.Adam([log_alpha], lr=args.alpha_lr)
  File "D:\Anaconda3\lib\site-packages\torch\optim\adam.py", line 81, in __init__
    super(Adam, self).__init__(params, defaults)
  File "D:\Anaconda3\lib\site-packages\torch\optim\optimizer.py", line 54, in __init__
    self.add_param_group(param_group)
  File "D:\Anaconda3\lib\site-packages\torch\optim\optimizer.py", line 269, in add_param_group
    raise ValueError("can't optimize a non-leaf Tensor")
ValueError: can't optimize a non-leaf Tensor
```

**Comment by Trinkle23897** [comment]
= torch.full(1, math.log(args.alpha), ...)

**Comment by jaried** [comment]
It's ok.

```python
log_alpha = torch.full((1,), np.log(args.alpha), requires_grad=True, device=args.device)
```
