### ISSUE TITLE
TypeError in batch's __setitem__ in the middle of training

### ISSUE THREAD

**Issue by robkuehl** [aai-institute/tianshou#665]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Version numbers:
0.4.8 0.19.0 1.10.1+cu102 1.21.5 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] linux

**My Issue:**
I am using Tianshou with a custom environment for my master thesis. I started several experiments, and some of the fail after several thousand steps. I do not assume it to be an issue of the environment, I do not have issues running stable baselines3.
I already searched through the source code, but I can't figure out why the exception is raised.
So far, the only similarity between the crashing experiments I could find is the use of action masking.
I know my issue is very specific, but I would appreciate any suggestion by what it my be caused and will try to supply any needed information.

**The training loop is build as follows:**
 ```python

# ------------- Create the replay buffer and the collector ---------------- #

    replaybuffer = ReplayBuffer(size=buffer_size)
    train_collector = Collector(policy, train_env, replaybuffer)

    # -------------------- Start Training ------------------------ #

    steps_done = 0
    continue_train = True
    logger.bind(console=True).info("Train agent for {} steps".format(num_steps_train))
    logger.bind(console=True).info("Sample size for one batch: {}".format(sample_size))
    while continue_train:
        # compute number of steps to collect in current interation
        steps_to_collect_iter = min(num_steps_train - steps_done, steps_to_collect)
        logger.bind(console=True).info("Collect {} steps".format(steps_to_collect_iter))

        # collect steps
        train_collector.collect(n_step=steps_to_collect_iter)
        if steps_to_collect_iter < steps_to_collect:
            # collected the last steps remaining
            continue_train = False

        # update policy if enough data is stored in buffer
        logger.bind(console=True).info(
            "Current length of buffer: {}".format(len(train_collector.buffer))
        )
        if len(train_collector.buffer) >= sample_size:
            logger.bind(console=True).info("Update Policy.")
            # only update policy if we collected enough data
            policy.update(
                sample_size=sample_size,
                buffer=train_collector.buffer,
                batch_size=int(batch_size),
                repeat=1,
            )
        steps_done = steps_done + steps_to_collect_iter

        if steps_done == num_steps_train:
            continue_train = False
  ```

**The Exception**

```python
2022-06-09T18:31:06.746305+0200 | INFO | Current length of buffer: 27170
2022-06-09T18:31:06.747065+0200 | INFO | Update Policy.
2022-06-09T18:31:11.224021+0200 | INFO | Collect 10 steps
Traceback (most recent call last):
  File "/p/fm/RobinKuehling/rl_intraday/src/run/run_dqn.py", line 546, in <module>
    if __name__ == "__main__":
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/p/fm/RobinKuehling/rl_intraday/src/run/run_dqn.py", line 482, in main
    # collect steps
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/tianshou/data/collector.py", line 275, in collect
    ptr, ep_rew, ep_len, ep_idx = self.buffer.add(
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/tianshou/data/buffer/base.py", line 242, in add
    self._meta[ptr] = batch
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/tianshou/data/batch.py", line 265, in __setitem__
    self.__dict__[key][index] = value[key]
  File "/u/k/kuehling/miniconda3/envs/rl_intraday_cluster/lib/python3.8/site-packages/tianshou/data/batch.py", line 265, in __setitem__
    self.__dict__[key][index] = value[key]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Trinkle23897** [comment]
Sorry for the delay.

Here is the reason: one of your environment's info values contains both numeric value and None, for example:
```
step 10: info == {"id": 123}
step 11: info == {"id": None}
```

The type of one attribute's value should be consistent in order to save memory and improve performance. Or another solution is:
```
step 11: info == {}
```

**Comment by robkuehl** [comment]
Thanks for the quick response, really appreciate your help! I indeed had None values in the info dict but I didn't think that it matters. I now replaced Nones and added a check to verify that the info dict does not contain None values. I will let you know in case it crashes anyway.

**Comment by robkuehl** [comment]
Experiments works fine, thanks for help!
