### ISSUE TITLE
Can the alpha_optim of the Sac algorithm be saved and read?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#676]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.8 0.21.0 1.11.0+cu113 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
My code is as follows, it seems that reading ckpt does not work:
I tried reading ckpt before `args.alpha = (target_entropy, log_alpha, alpha_optim)`, seems to be the problem too.
```python
    if args.auto_alpha:
        target_entropy = -np.prod(env.action_space.shape)
        log_alpha = torch.full((1,), np.log(args.alpha), requires_grad=True, device=args.device)
        alpha_optim = torch.optim.Adam([log_alpha], lr=args.alpha_lr)
        args.alpha = (target_entropy, log_alpha, alpha_optim)

    policy = SACPolicy(
        actor,
        actor_optim,
        critic1,
        critic1_optim,
        critic2,
        critic2_optim,
        tau=args.tau,
        gamma=args.gamma,
        alpha=args.alpha,
        reward_normalization=args.rew_norm,
        estimation_step=args.n_step,
        action_space=env.action_space,
        # deterministic_eval=False
    )
    if args.resume:
        try:
            checkpoint = torch.load(ckpt_file, map_location=args.device)
            policy.load_state_dict(checkpoint['model'])
            actor_optim.load_state_dict(checkpoint['actor_optim'])
            critic1_optim.load_state_dict(checkpoint['critic1_optim'])
            alpha_optim.load_state_dict(checkpoint['alpha_optim'])
        except Exception as e:
            print(e)
    result = offpolicy_trainer(
        policy,
        train_collector,
        test_collector,
        args.epoch,
        args.step_per_epoch,
        args.step_per_collect,
        args.test_num,
        args.batch_size,
        update_per_step=args.update_per_step,
        stop_fn=stop_fn,
        save_fn=save_fn,
        logger=logger,
        resume_from_log=args.resume,
        save_checkpoint_fn=save_checkpoint_fn
    )

```

```python
Traceback (most recent call last):
  File "test/continuous/test_sac_with_il.py", line 240, in <module>
    test_sac_with_il()
  File "test/continuous/test_sac_with_il.py", line 141, in test_sac_with_il
    critic1_optim.load_state_dict(checkpoint['critic1_optim'])
  File "/Users/trinkle23897/miniconda3/lib/python3.8/site-packages/torch/optim/optimizer.py", line 116, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'Adam' object is not subscriptable
```

**Comment by Trinkle23897** [comment]
Could you please paste your `save_checkpoint_fn` function? It works on my side.

```python
    def save_checkpoint_fn(epoch, env_step, gradient_step):
        # see also: https://pytorch.org/tutorials/beginner/saving_loading_models.html
        ckpt_path = os.path.join(log_path, f"checkpoint{epoch}.pth")
        # Example: saving by epoch num
        # ckpt_path = os.path.join(log_path, f"checkpoint_{epoch}.pth")
        torch.save(
            {
                "model": policy.state_dict(),
                "actor_optim": actor_optim.state_dict(),
                "critic1_optim": critic1_optim.state_dict(),
                "critic2_optim": critic2_optim.state_dict(),
                "alpha_optim": alpha_optim.state_dict(),
            }, ckpt_path
        )
        return ckpt_path
```

**Comment by jaried** [comment]
Does `critic2_optim` need to be saved? I have never saved.

```python
    def save_checkpoint_fn(epoch, env_step, gradient_step):
        global save_times
        save_times += 1
        save_path = os.path.join(ckpt_path, f'checkpoint_{save_times}.pth')
        try:
            torch.save(
                {
                    'model': policy.state_dict(),
                    'actor_optim': actor_optim.state_dict(),
                    'critic1_optim': critic1_optim.state_dict(),
                    'alpha_optim': alpha_optim.state_dict(),
                }, save_path
            )
        except Exception as e:
            print(e)
```

**Comment by Trinkle23897** [comment]
Modified from `test/continuous/test_sac_with_il.py`:

```python
import argparse
import os
import gym
import numpy as np
import pytest
import torch
from torch.utils.tensorboard import SummaryWriter

from tianshou.data import Collector, VectorReplayBuffer
from tianshou.policy import ImitationPolicy, SACPolicy
from tianshou.trainer import offpolicy_trainer
from tianshou.env import DummyVectorEnv
from tianshou.utils import TensorboardLogger
from tianshou.utils.net.common import Net
from tianshou.utils.net.continuous import Actor, ActorProb, Critic


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--task', type=str, default='Pendulum-v1')
    parser.add_argument('--reward-threshold', type=float, default=None)
    parser.add_argument('--seed', type=int, default=1)
    parser.add_argument('--buffer-size', type=int, default=20000)
    parser.add_argument('--actor-lr', type=float, default=1e-3)
    parser.add_argument('--critic-lr', type=float, default=1e-3)
    parser.add_argument('--il-lr', type=float, default=1e-3)
    parser.add_argument('--gamma', type=float, default=0.99)
    parser.add_argument('--tau', type=float, default=0.005)
    parser.add_argument('--alpha', type=float, default=0.2)
    parser.add_argument('--auto-alpha', type=int, default=1)
    parser.add_argument('--alpha-lr', type=float, default=3e-4)
    parser.add_argument('--epoch', type=int, default=5)
    parser.add_argument('--step-per-epoch', type=int, default=24000)
    parser.add_argument('--il-step-per-epoch', type=int, default=500)
    parser.add_argument('--step-per-collect', type=int, default=10)
    parser.add_argument('--update-per-step', type=float, default=0.1)
    parser.add_argument('--batch-size', type=int, default=128)
    parser.add_argument('--hidden-sizes', type=int, nargs='*', default=[128, 128])
    parser.add_argument('--resume', action='store_true', default=False)
    parser.add_argument(
        '--imitation-hidden-sizes', type=int, nargs='*', default=[128, 128]
    )
    parser.add_argument('--training-num', type=int, default=10)
    parser.add_argument('--test-num', type=int, default=100)
    parser.add_argument('--logdir', type=str, default='log')
    parser.add_argument('--render', type=float, default=0.)
    parser.add_argument('--rew-norm', action="store_true", default=False)
    parser.add_argument('--n-step', type=int, default=3)
    parser.add_argument(
        '--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu'
    )
    parser.add_argument('--ckpt-file', type=str, default='')
    args = parser.parse_known_args()[0]
    return args


def test_sac_with_il(args=get_args()):
    env = gym.make(args.task)
    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.action_shape = env.action_space.shape or env.action_space.n
    args.max_action = env.action_space.high[0]
    if args.reward_threshold is None:
        default_reward_threshold = {"Pendulum-v0": -250, "Pendulum-v1": -250}
        args.reward_threshold = default_reward_threshold.get(
            args.task, env.spec.reward_threshold
        )
    # you can also use tianshou.env.SubprocVectorEnv
    # train_envs = gym.make(args.task)
    train_envs = DummyVectorEnv(
        [lambda: gym.make(args.task) for _ in range(args.training_num)]
    )
    # test_envs = gym.make(args.task)
    test_envs = DummyVectorEnv(
        [lambda: gym.make(args.task) for _ in range(args.test_num)]
    )
    # seed
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    train_envs.seed(args.seed)
    test_envs.seed(args.seed)
    # model
    net = Net(args.state_shape, hidden_sizes=args.hidden_sizes, device=args.device)
    actor = ActorProb(
        net,
        args.action_shape,
        max_action=args.max_action,
        device=args.device,
        unbounded=True
    ).to(args.device)
    actor_optim = torch.optim.Adam(actor.parameters(), lr=args.actor_lr)
    net_c1 = Net(
        args.state_shape,
        args.action_shape,
        hidden_sizes=args.hidden_sizes,
        concat=True,
        device=args.device
    )
    critic1 = Critic(net_c1, device=args.device).to(args.device)
    critic1_optim = torch.optim.Adam(critic1.parameters(), lr=args.critic_lr)
    net_c2 = Net(
        args.state_shape,
        args.action_shape,
        hidden_sizes=args.hidden_sizes,
        concat=True,
        device=args.device
    )
    critic2 = Critic(net_c2, device=args.device).to(args.device)
    critic2_optim = torch.optim.Adam(critic2.parameters(), lr=args.critic_lr)

    if args.auto_alpha:
        target_entropy = -np.prod(env.action_space.shape)
        log_alpha = torch.full((1,), np.log(args.alpha), requires_grad=True, device=args.device)
        alpha_optim = torch.optim.Adam([log_alpha], lr=args.alpha_lr)
        args.alpha = (target_entropy, log_alpha, alpha_optim)

    policy = SACPolicy(
        actor,
        actor_optim,
        critic1,
        critic1_optim,
        critic2,
        critic2_optim,
        tau=args.tau,
        gamma=args.gamma,
        alpha=args.alpha,
        reward_normalization=args.rew_norm,
        estimation_step=args.n_step,
        action_space=env.action_space,
        # deterministic_eval=False
    )
    if args.resume:
        checkpoint = torch.load(args.ckpt_file, map_location=args.device)
        policy.load_state_dict(checkpoint['model'])
        actor_optim.load_state_dict(checkpoint['actor_optim'])
        critic1_optim.load_state_dict(checkpoint['critic1_optim'])
        critic2_optim.load_state_dict(checkpoint['critic2_optim'])
        alpha_optim.load_state_dict(checkpoint['alpha_optim'])
    # collector
    train_collector = Collector(
        policy,
        train_envs,
        VectorReplayBuffer(args.buffer_size, len(train_envs)),
        exploration_noise=True
    )
    test_collector = Collector(policy, test_envs)
    # train_collector.collect(n_step=args.buffer_size)
    # log
    log_path = os.path.join(args.logdir, args.task, 'sac')
    writer = SummaryWriter(log_path)
    logger = TensorboardLogger(writer)

    def save_best_fn(policy):
        torch.save(policy.state_dict(), os.path.join(log_path, 'policy.pth'))

    def stop_fn(mean_rewards):
        return mean_rewards >= args.reward_threshold

    def save_checkpoint_fn(epoch, env_step, gradient_step):
        # see also: https://pytorch.org/tutorials/beginner/saving_loading_models.html
        ckpt_path = os.path.join(log_path, f"checkpoint{epoch}.pth")
        # Example: saving by epoch num
        # ckpt_path = os.path.join(log_path, f"checkpoint_{epoch}.pth")
        torch.save(
            {
                "model": policy.state_dict(),
                "actor_optim": actor_optim.state_dict(),
                "critic1_optim": critic1_optim.state_dict(),
                "critic2_optim": critic2_optim.state_dict(),
                "alpha_optim": alpha_optim.state_dict(),
            }, ckpt_path
        )
        return ckpt_path

    # trainer
    result = offpolicy_trainer(
        policy,
        train_collector,
        test_collector,
        args.epoch,
        args.step_per_epoch,
        args.step_per_collect,
        args.test_num,
        args.batch_size,
        update_per_step=args.update_per_step,
        stop_fn=stop_fn,
        save_best_fn=save_best_fn,
        save_checkpoint_fn=save_checkpoint_fn,
        logger=logger
    )
    assert stop_fn(result['best_reward'])


if __name__ == '__main__':
    test_sac_with_il()
```

**Comment by jaried** [comment]
Thanks for your answer.
