### ISSUE TITLE
How to render mujoco

### ISSUE THREAD

**Issue by hungcao0402** [aai-institute/tianshou#682]
I try to render with my pretrained and have a bug. 
`python mujoco_ppo.py --watch --resume-path results/Ant-v3/ppo/8/220623-152204/policy.pth --render 0.003`

```python
/home/hungcao/workspace/cs106/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(
Observations shape: (111,)
Actions shape: (8,)
Action range: -1.0 1.0
Loaded agent from:  results/Ant-v3/ppo/8/220623-152204/policy.pth
/home/hungcao/workspace/cs106/lib/python3.8/site-packages/envpool/python/envpool.py:96: UserWarning: The `seed` function in envpool is abandoned. You can set seed by envpool.make(..., seed=seed) instead.
  warnings.warn(
Traceback (most recent call last):
  File "mujoco_ppo.py", line 233, in <module>
    test_ppo()
  File "mujoco_ppo.py", line 228, in test_ppo
    result = test_collector.collect(n_episode=args.test_num, render=args.render)
  File "/home/hungcao/workspace/cs106/lib/python3.8/site-packages/tianshou/data/collector.py", line 270, in collect
    self.env.render()
  File "/home/hungcao/workspace/cs106/lib/python3.8/site-packages/tianshou/env/venv_wrappers.py", line 60, in render
    return self.venv.render(**kwargs)
  File "/home/hungcao/workspace/cs106/lib/python3.8/site-packages/gym/core.py", line 170, in render
    raise NotImplementedError
NotImplementedError
```

**Comment by Trinkle23897** [comment]
You can switch back to gym mujoco to render. The simplest ways are either `pip uninstall envpool`, or modify the following code in `examples/mujoco/mujoco_env.py`:

```diff
- try:
-   import envpool
- except ImportError:
-   envpool = None
+ envpool = None
```
