### ISSUE TITLE
Why is the length of buffers 0 after reading an HDF5 file?

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#686]
-  I have marked all applicable categories:
-  I have visited the [source website](https://github.com/thu-ml/tianshou/)
-  I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
import tianshou, gym, torch, numpy, sys
print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.9 0.24.1 1.11.0+cu113 1.20.1 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] win32
```
I use the following code to save the buffer:
```python
buffers.save_hdf5(buffer_save_file, compression=True)
```
I use the following code to read the buffer, why is the length of the buffer 0?
```python
buffers = VectorReplayBuffer(args.buffer_size, len(train_envs))
train_collector = AsyncCollector(
    policy,
    train_envs,
    buffers,
    exploration_noise=True
)
buffers.load_hdf5(buffer_save_file)
print(buffers.__len__())
```
```
0
```
buffers.sample(1) also reports an error:
```python
D:\Anaconda3\lib\site-packages\tianshou\data\buffer\manager.py:175: RuntimeWarning: invalid value encountered in true_divide
  self.buffer_num, batch_size, p=self._lengths / self._lengths.sum()
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-4dc940388d87>", line 1, in <module>
    buffers.sample(1)
  File "D:\Anaconda3\lib\site-packages\tianshou\data\buffer\base.py", line 293, in sample
    indices = self.sample_indices(batch_size)
  File "D:\Anaconda3\lib\site-packages\tianshou\data\buffer\manager.py", line 174, in sample_indices
    buffer_idx = np.random.choice(
  File "mtrand.pyx", line 929, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```

**Comment by jaried** [comment]
```python
buffers=buffers.load_hdf5(buffer_save_file)
```
