### ISSUE TITLE
v0.4.9 run offline test_gail script throw venvs error

### ISSUE THREAD

**Issue by Rocky-L** [aai-institute/tianshou#744]
- [X] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)

  0.4.9 0.26.0 1.12.1 1.22.2 3.8.10 (default, Feb  9 2022, 23:36:40) 
  [Clang 13.0.0 (clang-1300.0.29.30)] darwin
  ```

Run Command:

```bash
$ python test/offline/test_gail.py
```

Traceback (most recent call last):
  File "test/offline/test_gail.py", line 232, in <module>
    test_gail()
  File "test/offline/test_gail.py", line 202, in test_gail
    result = onpolicy_trainer(
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/trainer/onpolicy.py", line 150, in onpolicy_trainer
    return OnpolicyTrainer(*args, **kwargs).run()
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/trainer/base.py", line 440, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/trainer/base.py", line 252, in __iter__
    self.reset()
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/trainer/base.py", line 237, in reset
    test_result = test_episode(
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/trainer/utils.py", line 27, in test_episode
    result = collector.collect(n_episode=n_episode)
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/data/collector.py", line 304, in collect
    result = self.env.step(action_remap, ready_env_ids)  # type: ignore
  File "/Users/elbert.li/projects/scripts/coach/tianshou/tianshou/env/venvs.py", line 272, in step
    obs, rew, done, info = self.workers[j].recv()  # type: ignore
ValueError: too many values to unpack (expected 4)

Any idea how to fix this issue?

**Comment by Trinkle23897** [comment]
Downgrade gym version to <=0.25

**Comment by Rocky-L** [comment]
> Downgrade gym version to <=0.25

Problem Solved!
