### ISSUE TITLE
Getting a error when trying to predict an action

### ISSUE THREAD

**Issue by ubuntuSync** [aai-institute/tianshou#808]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

versions:
0.4.11 0.26.2 1.13.1+cu117 1.23.5 3.9.16 (main, jan 11 2023, 16:05:54
[GCC 11.2.0] linux

running on : Ubuntu 22.04.1 LTS (GNU/Linux 5.15.79.1-microsoft-standard-WSL2 x86_64)

 ``` python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
env = gym.make('CartPole-v1')

net = Net(env.observation_space.shape[0], hidden_sizes=[32,32], device=device)
actor = Actor(net, env.action_space.n, device=device)
critic = Critic(net, device=device)
model = ActorCritic(actor, critic).to(device)
optim = torch.optim.Adam(model.parameters(), lr=1e-3)

dist = torch.distributions.Categorical
policy = PPOPolicy(actor, critic, optim, dist, action_space=env.action_space, deterministic_eval=True)
policy.load_state_dict(torch.load("ppo.pth"))

obs = env.reset()
done = False
while not done:
    env.render()
    action = policy(Batch(obs=np.array([obs]))).act[0]
    obs, reward, done, _, info = env.step(action)
 ```

error:
 ```
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/DataSpell 2022.3.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/mnt/c/Program Files/JetBrains/DataSpell 2022.3.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/c/Users/name/DataspellProjects/dsProject/reinforcementLearning/ppo/ppo_test.py", line 29, in <module>
    action = policy(Batch(obs=np.array([obs]))).act[0]
  File "/home/name/anaconda3/envs/TF-GPU/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/name/anaconda3/envs/TF-GPU/lib/python3.9/site-packages/tianshou/policy/modelfree/pg.py", line 108, in forward
    logits, hidden = self.actor(batch.obs, state=state, info=batch.info)
  File "/home/name/anaconda3/envs/TF-GPU/lib/python3.9/site-packages/tianshou/data/batch.py", line 208, in __getattr__
    return getattr(self.__dict__, key)
AttributeError: 'dict' object has no attribute 'info' ```

**Comment by Trinkle23897** [comment]
Try this:
```python
action = policy(Batch(obs=np.array([obs]), info={})).act[0]
```
