### ISSUE TITLE
 object of type 'TimeLimit' has no len()

### ISSUE THREAD

**Issue by zzz0906** [aai-institute/tianshou#832]
I found out that in the testing code, my env is CartPole-V1
When I do this in my own code.
```
env = gym.make(args.task)
print (env.__class__)
print(isinstance(env, gym.Env))
```
I will have this output
```
<class 'gymnasium.wrappers.time_limit.TimeLimit'>
True
```
But when I modify the collector.py as below
```
print (env.__class__)
print(isinstance(env, gym.Env))
super().__init__()
if isinstance(env, gym.Env) and not hasattr(env, "__len__"):
  warnings.warn("Single environment detected, wrap to DummyVectorEnv.")
  self.env = DummyVectorEnv([lambda: env])  # type: ignore 
  print('dummy activate!')
```
it will output
```
<class 'gymnasium.wrappers.time_limit.TimeLimit'>
False
```
and raised error as below：
```
Traceback (most recent call last):
  File "/home/charlie/NeuralCollapse/NeuralCollapse4RL/classic/DQN.py", line 175, in <module>
    test_dqn(get_args())
  File "/home/charlie/NeuralCollapse/NeuralCollapse4RL/classic/DQN.py", line 161, in test_dqn
    collector = Collector(policy, env)
  File "/home/charlie/anaconda3/envs/tianshou/lib/python3.10/site-packages/tianshou/data/collector.py", line 77, in __init__
    self.env_num = len(self.env)
```
- I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
  ```
  0.4.11 0.27.1 1.13.1.post200 1.23.5 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] linux
  ```

**Comment by Trinkle23897** [comment]
You need to upgrade to version 0.5.0 via `pip install tianshou --upgrade` or pull the latest master code and `pip install -e .`. This issue has been fixed.
