### ISSUE TITLE
[Bug] Failing Envpool support for examples/box2d/lunarlander_dqn.py

### ISSUE THREAD

**Issue by samholt** [aai-institute/tianshou#841]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
> `0.5.1 0.28.1 2.0.0+cu117 1.23.5 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] linux`

---

Hi Tianshou Team,

I love tianshou, however I am trying to use it with `envpool` specifically with the box2d env LunarLander.

Following https://tianshou.readthedocs.io/en/master/tutorials/cheatsheet.html#envpool-integration if I modify the example of `examples/box2d/lunarlander_dqn.py`, by changing the lines only to:

```
from envpool import make_gymnasium

...

    env = make_gymnasium(args.task)
    args.state_shape = env.observation_space.shape or env.observation_space.n
    args.action_shape = env.action_space.shape or env.action_space.n
    # train_envs = make_gymnasium(args.task)
    # you can also use tianshou.env.SubprocVectorEnv
    train_envs = DummyVectorEnv(
        [lambda: make_gymnasium(args.task) for _ in range(args.training_num)]
    )
    # test_envs = make_gymnasium(args.task)
    test_envs = SubprocVectorEnv(
        [lambda: make_gymnasium(args.task) for _ in range(args.test_num)]
    )

```

I get the following error when I run this

```
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sam/.vscode-server/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/sam/.vscode-server/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/sam/.vscode-server/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/sam/.vscode-server/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/sam/.vscode-server/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/sam/.vscode-server/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/sam/code/tmp/tianshou/examples/box2d/lunarlander_dqn.py", line 152, in <module>
    test_dqn(get_args())
  File "/home/sam/code/tmp/tianshou/examples/box2d/lunarlander_dqn.py", line 101, in test_dqn
    train_collector.collect(n_step=args.batch_size * args.training_num)
  File "/home/sam/code/tmp/tianshou/tianshou/data/collector.py", line 295, in collect
    obs_next, rew, terminated, truncated, info = self.env.step(
  File "/home/sam/code/tmp/tianshou/tianshou/env/venvs.py", line 341, in step
    self.workers[j].send(action[i])
  File "/home/sam/code/tmp/tianshou/tianshou/env/worker/dummy.py", line 38, in send
    self.result = self.env.step(action)  # type: ignore
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/site-packages/envpool/python/envpool.py", line 143, in step
    self.send(action, env_id)
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/site-packages/envpool/python/envpool.py", line 121, in send
    self._check_action(action)
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/site-packages/envpool/python/envpool.py", line 39, in _check_action
    raise RuntimeError(
RuntimeError: Expected dtype int32 with action "action", got int64

```

Even if I modify the type explicitly, it further breaks with sending individual actions to env.step() rather than sending an array of actions.

Could you clarify how I can use the envpool environments with tianshou? Possibly showing an example, or how to modify one of the existing examples such that it works? I really would like to use this DQN example on the `'LunarLander-v2'` env with envpool.

Keep up the great work,

Thank you so much for your time,

All the best,
Sam

**Comment by Trinkle23897** [comment]
As the traceback shows, can you modify the network output tensor type to int32 instead of int64?

**Comment by samholt** [comment]
Hi @Trinkle23897 

I agree with you. When I do modify the network output tensor type to int32 instead of int64 as you suggest it reveals this more fundamental error:

```
Traceback (most recent call last):
  File "/home/sam/code/tmp/tianshou/examples/box2d/lunarlander_dqn.py", line 152, in <module>
    test_dqn(get_args())
  File "/home/sam/code/tmp/tianshou/examples/box2d/lunarlander_dqn.py", line 101, in test_dqn
    train_collector.collect(n_step=args.batch_size * args.training_num)
  File "/home/sam/code/tmp/tianshou/tianshou/data/collector.py", line 295, in collect
    obs_next, rew, terminated, truncated, info = self.env.step(
  File "/home/sam/code/tmp/tianshou/tianshou/env/venvs.py", line 341, in step
    self.workers[j].send(action[i])
  File "/home/sam/code/tmp/tianshou/tianshou/env/worker/dummy.py", line 38, in send
    self.result = self.env.step(action)  # type: ignore
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/site-packages/envpool/python/envpool.py", line 143, in step
    self.send(action, env_id)
  File "/home/sam/anaconda3/envs/tia/lib/python3.9/site-packages/envpool/python/envpool.py", line 122, in send
    self._send(action)
TypeError: _send(): incompatible function arguments. The following argument types are supported:
    1. (self: envpool.box2d.box2d_envpool._LunarLanderDiscreteEnvPool, arg0: List[numpy.ndarray]) -> None

Invoked with: LunarLanderDiscreteGymnasiumEnvPool(num_envs=1, batch_size=1, num_threads=0, max_num_players=1, thread_affinity_offset=-1, base_path='/home/sam/anaconda3/envs/tia/lib/python3.9/site-packages/envpool', seed=42, gym_reset_return_info=True, max_episode_steps=1000, reward_threshold=200.0), [array([0], dtype=int32), array([0], dtype=int32), 1]
```

Could you advise on how to solve this error?

Thank you so much for your time,

All the best,
Sam

**Comment by Trinkle23897** [comment]
can you print your action? It seems like the action you send to envpool is `[array([0], dtype=int32), array([0], dtype=int32), 1]`, which are not all numpy array

**Comment by Trinkle23897** [comment]
oh, I know the issue. You should not create a SubprocVectorEnv on top of envpool because envpool itself is already a vector env. please refer to this example: https://github.com/thu-ml/tianshou/blob/4ac407c78f58102fa7f38ded6bfc1e42c703a4a7/examples/atari/atari_wrapper.py#L327-L342

**Comment by samholt** [comment]
Great, thank you @Trinkle23897 !

That solves the issue,

Best,
Sam
