### ISSUE TITLE
how to return multiple rnn internal state value?

### ISSUE THREAD

**Issue by db005** [aai-institute/tianshou#855]
0.5.0 0.27.1 2.0.0 1.23.5 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)] win32
```
Traceback (most recent call last):
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\buffer\manager.py", line 148, in add
    self._meta[ptrs] = batch
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\batch.py", line 270, in __setitem__
    self.__dict__[key][index] = value[key]
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\batch.py", line 264, in __setitem__
    raise ValueError("Creating keys is not supported by item assignment.")
ValueError: Creating keys is not supported by item assignment.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\workspace\hebbrl\main.py", line 191, in <module>
    result = ts.trainer.offpolicy_trainer(
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\trainer\offpolicy.py", line 133, in offpolicy_trainer
    return OffpolicyTrainer(*args, **kwargs).run()
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\trainer\base.py", line 441, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\trainer\base.py", line 252, in __iter__
    self.reset()
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\trainer\base.py", line 237, in reset
    test_result = test_episode(
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\trainer\utils.py", line 27, in test_episode
    result = collector.collect(n_episode=n_episode)
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\collector.py", line 328, in collect
    ptr, ep_rew, ep_len, ep_idx = self.buffer.add(
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\buffer\manager.py", line 161, in add
    self._meta[ptrs] = batch
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\batch.py", line 270, in __setitem__
    self.__dict__[key][index] = value[key]
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\batch.py", line 270, in __setitem__
    self.__dict__[key][index] = value[key]
  File "F:\Users\miaoy\anaconda3\envs\tianshou\lib\site-packages\tianshou\data\batch.py", line 270, in __setitem__
    self.__dict__[key][index] = value[key]
  [Previous line repeated 1 more time]
RuntimeError: shape mismatch: value tensor of shape [3, 80, 4] cannot be broadcast to indexing result of shape [1, 80, 4]
```
```

    def forward(self, obs, state=None, info={}, Train=False, r = None):
        if not isinstance(obs, torch.Tensor):
            obs = torch.tensor(obs, dtype=torch.float32).to(device)
        if len(obs.shape)==2:
            obs = obs.view(-1,1,obs.shape[1])
        # batch = obs.shape[0]
        # L = obs.shape[1]
        self.L = obs.shape[1]
        logits1 = F.relu(self.L1(obs))#.view(batch, L, -1))) 
        logits2 = F.relu(self.L2(logits1)) 
        logits3 = self.L3(logits2).view(-1,3)
        # logits = logits.view(batch,L,-1)
        if r == None or len(r.shape)==0:
            return logits3, state
        if Train==False:
            if state==None:
                state = {"0":{"h":None,"c":None},"1":{"h":None,"c":None},"2":{"h":None,"c":None}}
            rnnOutput, hidden0 = self.Conv1d2RNNInput(self.L1, obs, r, 2, state = [state["0"]["h"],state["0"]["c"]])
            self.RNN2Conv1dParam(self.L1, rnnOutput)
            rnnOutput, hidden1 = self.Conv1d2RNNInput(self.L2, logits1, r, 1, state = [state["1"]["h"],state["1"]["c"]])
            self.RNN2Conv1dParam(self.L2, rnnOutput)
            rnnOutput, hidden2 = self.Conv1d2RNNInput(self.L3, logits2, r, state = [state["2"]["h"],state["2"]["c"]])
            self.RNN2Conv1dParam(self.L3, rnnOutput)
        return logits3, {"0":{"h":hidden0[0],"c":hidden0[1]},"1":{"h":hidden1[0],"c":hidden1[1]},"2":{"h":hidden2[0],"c":hidden2[1]}}
```

**Comment by db005** [comment]
Hello! I set up two layers of dict to store rnn intermediate state. How to set the intermediate state of multi-layer rnn？@Trinkle23897

**Comment by db005** [comment]
我怀疑是bug，因为我用例子的代码也是这个报错。

**Comment by db005** [comment]
I have carefully examined and thought about this issue. I found that my lstm has three layers, and the shape of his state should be (num_layers, bsz, dim). My num_layers is 3, but the code wants to broadcast [3, 80, 4] to [1, 80, 4].

**Comment by Trinkle23897** [comment]
You should return a state with type `dict[str, torch.Tensor]` where the tensor shape is `[bsz, len, ...]` (and it will be the same as input `state`). You are returning `dict[str, dict[str, torch.Tensor]]` which will be messed up in collector.
See examples here: https://github.com/thu-ml/tianshou/blob/1423eeb3b2828e1ffa03b0a2a2ae13473a82713a/tianshou/utils/net/continuous.py#L310-L314

In your case it should be something like
```py
return logits3, {
  "h": ..., # hidden[0] with shape [bsz, len, ...]
  "c": ..., # hidden[1] with shape [bsz, len, ...]
}
```
