### ISSUE TITLE
something bug about the file in examples/inverse/irl_gail.py

### ISSUE THREAD

**Issue by lzl60109** [aai-institute/tianshou#926]
Hello, I would like to ask, I just run the irl_gail.py file you gave, why the following error occurs?

**Traceback (most recent call last):
  File "examples/run_gail.py", line 267, in <module>
    test_gail()
  File "examples/run_gail.py", line 98, in test_gail
    train_envs = SubprocVectorEnv(
  File "/home/liang/miniconda3/envs/adroit_gail/lib/python3.8/site-packages/tianshou/env/venvs.py", line 459, in __init__
    super().__init__(env_fns, worker_fn, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'norm_obs'**

**Comment by lzl60109** [comment]
1
