### ISSUE TITLE
BrokenPipeError: [WinError 109] 管道已结束

### ISSUE THREAD

**Issue by lgx0044** [aai-institute/tianshou#954]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

```
import tianshou, torch, numpy, sys
print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.5.1 1.13.1+cu117 1.24.4 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)] win32
```

Hello, thanks for your project!
I meet some problems when I train a bdqn agent in my env. Here is the console log.

```
MultiDiscrete([3 3 3 3])
MultiDiscrete([3 3 3 3]) Box(-inf, inf, (5,), float32)
Observations shape: (5,)
Num branches: 4
Actions per branch: 3
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\mxd\.conda\envs\ts\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\mxd\.conda\envs\ts\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\worker\subproc.py", line 81, in _worker
    env = env_fn_wrapper.data()
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\venvs.py", line 40, in patched
    assert callable(
AssertionError: Env generators that are provided to vector environemnts must be callable.
Traceback (most recent call last):
  File "C:\Users\mxd\.conda\envs\ts\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/mxd/Desktop/MXD_control/ABS/tianshou_main.py", line 167, in <module>
    test_bdq(get_args())
  File "c:/Users/mxd/Desktop/MXD_control/ABS/tianshou_main.py", line 74, in test_bdq
    train_envs = SubprocVectorEnv(
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\venvs.py", line 455, in __init__
    super().__init__(env_fns, worker_fn, **kwargs)
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\venvs.py", line 149, in __init__
    self.workers = [worker_fn(_patch_env_generator(fn)) for fn in env_fns]
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\venvs.py", line 149, in <listcomp>
    self.workers = [worker_fn(_patch_env_generator(fn)) for fn in env_fns]
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\venvs.py", line 453, in worker_fn
    return SubprocEnvWorker(fn, share_memory=False)
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\worker\subproc.py", line 148, in __init__
    super().__init__(env_fn)
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\worker\base.py", line 18, in __init__
    self.action_space = self.get_env_attr("action_space")  # noqa: B009
  File "C:\Users\mxd\.conda\envs\ts\lib\site-packages\tianshou\env\worker\subproc.py", line 152, in get_env_attr
    return self.parent_remote.recv()
  File "C:\Users\mxd\.conda\envs\ts\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\mxd\.conda\envs\ts\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
```
And my custom environment is implemented through a pkl file, here is some of the code：

```
class Venv6(gym.Env):
    def __init__(self, config=config6, eval=False) -> None:
        super().__init__()
        self.config = config
        venv_path = self.config["env_path"]
        self.venv = pickle.load(open(venv_path, 'rb'), encoding='utf-8')
       ....
        # 多维离散动作空间 3 3 3 3
        self.action_space = gym.spaces.MultiDiscrete([3, 3, 3, 3])
        self.observation_space = gym.spaces.Box(
            low=-np.inf, high=np.inf, shape=(5,), dtype=np.float32)
    def reset(self):
        self.state = np.zeros((lenth,))
        self.inf = {}
        ...
        return self.state, self.inf
    def step(self, action):
        ...
        venv_input = {**self.state_input, **self.action_input}
        output = self.venv.infer_one_step(venv_input)
       ...
        return self.state, reward, self.done, False, self.inf
```

**Comment by lgx0044** [comment]
When I don't use SubprocVectorEnv, the problem is solved.
```
    train_envs = Venv6()
    test_envs = Venv6()

```
