### ISSUE TITLE
gymnasium.error.NameNotFound: Environment `PongNoFrameskip` doesn't exist.

### ISSUE THREAD

**Issue by whbeats** [aai-institute/tianshou#983]
When I ran `atari_dqn.py` after installation, I saw the following error:

```
H:\002_tianshou\tianshou-master\examples\atari\atari_wrapper.py:352: UserWarning: Recommend using envpool (pip install envpool) to run Atari games more efficiently.
  warnings.warn(
Traceback (most recent call last):
  File "H:\002_tianshou\tianshou-master\examples\atari\atari_dqn.py", line 263, in <module>
    test_dqn(get_args())
  File "H:\002_tianshou\tianshou-master\examples\atari\atari_dqn.py", line 87, in test_dqn
    env, train_envs, test_envs = make_atari_env(
                                 ^^^^^^^^^^^^^^^
  File "H:\002_tianshou\tianshou-master\examples\atari\atari_wrapper.py", line 355, in make_atari_env
    env = wrap_deepmind(task, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\002_tianshou\tianshou-master\examples\atari\atari_wrapper.py", line 303, in wrap_deepmind
    env = gym.make(env_id)
          ^^^^^^^^^^^^^^^^
  File "F:\AcademicTools\Anaconda\envs\RL\Lib\site-packages\gymnasium\envs\registration.py", line 741, in make
    env_spec = _find_spec(id)
               ^^^^^^^^^^^^^^
  File "F:\AcademicTools\Anaconda\envs\RL\Lib\site-packages\gymnasium\envs\registration.py", line 527, in _find_spec
    _check_version_exists(ns, name, version)
  File "F:\AcademicTools\Anaconda\envs\RL\Lib\site-packages\gymnasium\envs\registration.py", line 393, in _check_version_exists
    _check_name_exists(ns, name)
  File "F:\AcademicTools\Anaconda\envs\RL\Lib\site-packages\gymnasium\envs\registration.py", line 370, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `PongNoFrameskip` doesn't exist.
```

I really hope someone can answer what's going wrong, thanks in advance!

**Comment by Trinkle23897** [comment]
You need to install ALE together, see https://github.com/Farama-Foundation/Gymnasium#installation, i.e., `pip install gymnasium[atari]` instead of `pip install gymnasium`

**Comment by MischaPanch** [comment]
Closing as answered

**Comment by chengzhen123** [comment]
> You need to install ALE together, see https://github.com/Farama-Foundation/Gymnasium#installation, i.e., `pip install gymnasium[atari]` instead of `pip install gymnasium`

I have installed gymnasium[atari] with `pip install gymnasium[atari]`,but it was not solved

**Comment by zzk2021** [comment]
same question with you. this project really support 3.1x python on Windows?

**Comment by macv666** [comment]
You can add 'import ale_py' at the top of your code scripts.
